// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GUIQvB8Cq706la37fBjWPL6Cdxnoc9s',
    appId: '1:198570716547:web:659c1acbf76c7b694e1ab6',
    messagingSenderId: '198570716547',
    projectId: 'sportreplay-44523',
    authDomain: 'sportreplay-44523.firebaseapp.com',
    storageBucket: 'sportreplay-44523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_J6M-Abv05EKWMdkIVCRAVtmUGr5hqGs',
    appId: '1:198570716547:android:c1b122ba641605314e1ab6',
    messagingSenderId: '198570716547',
    projectId: 'sportreplay-44523',
    storageBucket: 'sportreplay-44523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYhh0XroJoIzOCunjCOdGt_obS1G4ikDY',
    appId: '1:198570716547:ios:da18c1c2ec6f13594e1ab6',
    messagingSenderId: '198570716547',
    projectId: 'sportreplay-44523',
    storageBucket: 'sportreplay-44523.firebasestorage.app',
    iosBundleId: 'com.example.sportReplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYhh0XroJoIzOCunjCOdGt_obS1G4ikDY',
    appId: '1:198570716547:ios:da18c1c2ec6f13594e1ab6',
    messagingSenderId: '198570716547',
    projectId: 'sportreplay-44523',
    storageBucket: 'sportreplay-44523.firebasestorage.app',
    iosBundleId: 'com.example.sportReplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9GUIQvB8Cq706la37fBjWPL6Cdxnoc9s',
    appId: '1:198570716547:web:76af7515f2a6427a4e1ab6',
    messagingSenderId: '198570716547',
    projectId: 'sportreplay-44523',
    authDomain: 'sportreplay-44523.firebaseapp.com',
    storageBucket: 'sportreplay-44523.firebasestorage.app',
  );
}
